/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useControls } from 'leva'
import { useSnapshot } from 'valtio'
import state from "../../../state/state";
import { LoopOnce } from 'three';
export default function ChessBoard(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/chess_board.glb')
  const { actions } = useAnimations(animations, group)



const snapshot = useSnapshot(state);


useEffect(() => {
    if (snapshot.step === 6 && snapshot.reverse === false) {
      console.log("Play Animation");
      const action = actions['Take 001']; // Reference the animation by its name
      if (action) {
        action.reset().setLoop(LoopOnce, 1).clampWhenFinished = true; // Reset, set loop to once, and clamp when finished
        action.play(); // Play the animation
      }
    }
  }, [snapshot.step, snapshot.reverse, actions]);  // Include necessary dependencies



  const [Position, setPosition] = useState([7,0,5]);
  const [chessScale, setChessScale] = useState([0.7,0.7,0.7])
    useEffect(() => {
      const handleResize = () => {
        // Adjust xPosition based on screen size
        const screenWidth = window.innerWidth;
        if (screenWidth < 768) {
          // Adjust this breakpoint according to your design
         setPosition([0,-7,0])
         setChessScale([0.5,0.5,0.5])
        } else {
            setPosition([7,0,5])
         setChessScale([0.7,0.7,0.7])
        }
  
  
  
  
  
      };
  
      handleResize(); // Call it once to set initial position
  
      window.addEventListener("resize", handleResize);
      return () => window.removeEventListener("resize", handleResize);
    }, []);


  return (
    <group ref={group} {...props} dispose={null} position={Position} scale={chessScale}>
      <group name="Scene">
        <group name="RootNode" scale={0.024}>
          <group name="B_Bishop_1" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Bishop_1_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Bishop_1_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Bishop_2" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Bishop_2_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Bishop_2_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_King" position={[1.237, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_King_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_King_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Knight_1" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Knight_1_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Knight_1_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Knight_2" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Knight_2_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Knight_2_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Pawn_1" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Pawn_1_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Pawn_1_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Pawn_2" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Pawn_2_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Pawn_2_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Pawn_4" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Pawn_4_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Pawn_4_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Pawn_5" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Pawn_5_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Pawn_5_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Pawn_6" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Pawn_6_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Pawn_6_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Pawn_7" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Pawn_7_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Pawn_7_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Pawn_8" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Pawn_8_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Pawn_8_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Queen" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Queen_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Queen_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Rook_1" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Rook_1_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Rook_1_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group name="B_Rook_2" position={[-4.418, 0, 9.582]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="B_Rook_2_01_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['B_Rook_2_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
          </group>
          <group
            name="W_Bishop_1"
            position={[0.888, 0, 7.95]}
            rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Bishop_1_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Bishop_1_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group
            name="W_Bishop_2"
            position={[0.888, 0, 7.95]}
            rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Bishop_2_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Bishop_2_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group name="W_King" position={[0.888, 0, -60.844]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_King_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_King_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group
            name="W_Knight_1"
            position={[0.888, 0, 7.95]}
            rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Knight_1_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Knight_1_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group
            name="W_Knight_2"
            position={[0.888, 0, 7.95]}
            rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Knight_2_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Knight_2_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group name="W_Pawn_2" position={[0.888, 0, 7.95]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Pawn_2_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Pawn_2_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group name="W_Pawn_4" position={[0.888, 0, 7.95]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Pawn_4_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Pawn_4_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group name="W_Pawn_5" position={[0.888, 0, 7.95]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Pawn_5_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Pawn_5_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group name="W_Pawn_6" position={[0.888, 0, 7.95]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Pawn_6_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Pawn_6_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group name="W_Pawn_7" position={[0.888, 0, 7.95]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Pawn_7_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Pawn_7_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group name="W_Pawn_8" position={[0.888, 0, 7.95]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Pawn_8_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Pawn_8_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group name="W_Queen" position={[0.888, 0, 76.745]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Queen_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Queen_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group name="W_Rook_1" position={[0.888, 0, 7.95]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Rook_1_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Rook_1_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
          <group name="W_Rook_2" position={[0.888, 0, 7.95]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh
              name="W_Rook_2_02_-_Default_0"
              castShadow
              receiveShadow
              geometry={nodes['W_Rook_2_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
          </group>
        </group>
        <mesh
          name="B_Pawn_3_01_-_Default_0"
          castShadow
          receiveShadow
          geometry={nodes['B_Pawn_3_01_-_Default_0'].geometry}
          material={materials['01_-_Default']}
          position={[-0.105, 0, 0.227]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.024}
        />
        <mesh
          name="Chess_Board_02_-_Default_0"
          castShadow
          receiveShadow
          geometry={nodes['Chess_Board_02_-_Default_0'].geometry}
          material={materials['02_-_Default_0']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.024}
        />
        <mesh
          name="Chess_Board_03_-_Default_0"
          castShadow
          receiveShadow
          geometry={nodes['Chess_Board_03_-_Default_0'].geometry}
          material={materials['03_-_Default']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.024}
        />
        <mesh
          name="Chess_Board_07_-_Default_0"
          castShadow
          receiveShadow
          geometry={nodes['Chess_Board_07_-_Default_0'].geometry}
          material={materials['07_-_Default']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.024}
        />
        <mesh
          name="Chess_Board_08_-_Default_0"
          castShadow
          receiveShadow
          geometry={nodes['Chess_Board_08_-_Default_0'].geometry}
          material={materials['08_-_Default']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.024}
        />
        <mesh
          name="W_Pawn_1_02_-_Default_0"
          castShadow
          receiveShadow
          geometry={nodes['W_Pawn_1_02_-_Default_0'].geometry}
          material={materials['02_-_Default']}
          position={[0.021, 0, 0.189]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={0.024}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/chess_board.glb')
